# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MobileAxxess' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileAxxess
pod 'SDWebImage', '~> 5.5.2'
pod 'Alamofire', '~> 4.8.2'
pod 'SnapKit', '~> 5.0.0'
end
